### ISSUE TITLE
HeadObject 403 throws "Failed to parse response as 'restXml'"

### ISSUE THREAD

**Issue by joeeinertson-gravie** [awslabs/aws-sdk-kotlin#1368]
### Describe the bug

When making a HeadObject call, if the correct permissions are not granted, resulting in a 403 Forbidden response from AWS, the SDK fails with a deserialization error.

### Expected behavior

SDK should throw an error with a relevant error message

### Current behavior

SDK throws `aws.sdk.kotlin.services.s3.model.S3Exception: Failed to parse response as 'restXml'`

Full stacktrace:
```
aws.sdk.kotlin.services.s3.model.S3Exception: Failed to parse response as 'restXml' error, Request ID: 7NQ2X7PRGZFBB940, Extended request ID: OtgUPnKRDAVgcebkFyDl2QkKDRLjJaNVfv76BpKhFuax71AMAOE2Q85HiXqco5BJv4f9scsU9yc=
	at aws.sdk.kotlin.services.s3.serde.HeadObjectOperationDeserializerKt.throwHeadObjectError(HeadObjectOperationDeserializer.kt:101) ~[task/:?]
	at aws.sdk.kotlin.services.s3.serde.HeadObjectOperationDeserializerKt.access$throwHeadObjectError(HeadObjectOperationDeserializer.kt:1) ~[task/:?]
	at aws.sdk.kotlin.services.s3.serde.HeadObjectOperationDeserializer.deserialize(HeadObjectOperationDeserializer.kt:33) ~[task/:?]
	at aws.sdk.kotlin.services.s3.serde.HeadObjectOperationDeserializer.deserialize(HeadObjectOperationDeserializer.kt:28) ~[task/:?]
	at aws.smithy.kotlin.runtime.http.operation.DeserializeHandler.call(SdkOperationExecution.kt:341) ~[task/:?]
	at aws.smithy.kotlin.runtime.http.operation.DeserializeHandler$call$1.invokeSuspend(SdkOperationExecution.kt) ~[task/:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[task/:?]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104) ~[task/:?]
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277) ~[task/:?]
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95) ~[task/:?]
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69) ~[task/:?]
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source) ~[task/:?]
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48) ~[task/:?]
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source) ~[task/:?]
	at [snip]
Caused by: java.lang.IllegalStateException: unable to parse error from empty response
	at aws.sdk.kotlin.services.s3.serde.HeadObjectOperationDeserializerKt.throwHeadObjectError(HeadObjectOperationDeserializer.kt:97) ~[task/:?]
	... 23 more
```

### Steps to Reproduce

Run code like the following, but where you do not have permissions to read from the provided bucket.

```kotlin
S3Client.fromEnvironment().use { s3Client ->
  s3Client.headObject(
    HeadObjectRequest {
      bucket = "..."
      key = "..."
    }
  )
}
```

### AWS SDK for Kotlin version

1.2.54

### Platform (JVM/JS/Native)

JVM

### Operating system and version

OSX 14.5

**Comment by joeeinertson-gravie** [comment]
After some more investigation, it appears this happens not when a key doesn't exist in a bucket, but rather when a 403 Forbidden response is returned. I have updated the ticket title and description to reflect this.

**Comment by lauzadis** [comment]
Related to https://github.com/awslabs/aws-sdk-kotlin/issues/152

**Comment by lauzadis** [comment]
Hello, thanks for the report. A fix has been merged and should be available in the next release **v1.3.11**, currently scheduled for tomorrow.

**Comment by renke0** [comment]
> After some more investigation, it appears this happens not when a key doesn't exist in a bucket, but rather when a 403 Forbidden response is returned. I have updated the ticket title and description to reflect this.

I am still seeing this behavior on version 1.4.22. Was it fixed as well?

**Comment by lauzadis** [comment]
I'm unable to reproduce the issue on v1.4.22, I'm seeing the correct exception thrown:
`Exception in thread "main" aws.sdk.kotlin.services.s3.model.S3Exception: Service returned error code 403: Forbidden, Error type: Unknown, Protocol response: HTTP 403 Forbidden, Request ID: <REDACTED>, Extended request ID: <REDACTED>`

Can you please open a new GitHub issue and provide a minimal reproduction? Thanks.
