### ISSUE TITLE
SocketException while uploading a chunk for mulitpart upload

### ISSUE THREAD

**Issue by sdhuka** [awslabs/aws-sdk-kotlin#573]
### Describe the bug

Using the code below to upload a chunk(using default httpEngine) for a multipart uploads results in socket exception.

```
private fun ByteStream.Companion.chunk(
        file: File,
        start: Long,
        length: Long
    ): ByteStream {
        return object : ByteStream.OneShotStream() {
            override fun readFrom(): SdkByteReadChannel {
                return file.readChannel(start, start + length - 1)
            }
        }
    }
```

### Expected behavior

File chunk should be successfully uploaded to S3.

### Current behavior

File chunk uploads fails with below exception.

```
2022-04-05 09:30:57.899 4032-5187/com.example.storage_sample_new W/System.err: [DefaultDispatcher-worker-12] ERROR aws.smithy.kotlin.runtime.http.engine.ktor.KtorEngine - throwing(java.net.SocketException: Broken pipe)
2022-04-05 09:30:57.899 4032-5187/com.example.storage_sample_new W/System.err: java.net.SocketException: Broken pipe
2022-04-05 09:30:57.900 4032-5187/com.example.storage_sample_new W/System.err:     at java.net.SocketOutputStream.socketWrite0(Native Method)
2022-04-05 09:30:57.900 4032-5187/com.example.storage_sample_new W/System.err:     at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:117)
2022-04-05 09:30:57.900 4032-5187/com.example.storage_sample_new W/System.err:     at java.net.SocketOutputStream.write(SocketOutputStream.java:161)
2022-04-05 09:30:57.900 4032-5187/com.example.storage_sample_new W/System.err:     at com.android.org.conscrypt.ConscryptEngineSocket$SSLOutputStream.writeToSocket(ConscryptEngineSocket.java:724)
2022-04-05 09:30:57.900 4032-5187/com.example.storage_sample_new W/System.err:     at com.android.org.conscrypt.ConscryptEngineSocket$SSLOutputStream.writeInternal(ConscryptEngineSocket.java:698)
2022-04-05 09:30:57.900 4032-5187/com.example.storage_sample_new W/System.err:     at com.android.org.conscrypt.ConscryptEngineSocket$SSLOutputStream.write(ConscryptEngineSocket.java:661)
2022-04-05 09:30:57.901 4032-5187/com.example.storage_sample_new W/System.err:     at okio.OutputStreamSink.write(JvmOkio.kt:53)
2022-04-05 09:30:57.901 4032-5187/com.example.storage_sample_new W/System.err:     at okio.AsyncTimeout$sink$1.write(AsyncTimeout.kt:103)
2022-04-05 09:30:57.901 4032-5187/com.example.storage_sample_new W/System.err:     at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:255)
2022-04-05 09:30:57.901 4032-5187/com.example.storage_sample_new W/System.err:     at okio.RealBufferedSink.write(RealBufferedSink.kt:146)
2022-04-05 09:30:57.901 4032-5187/com.example.storage_sample_new W/System.err:     at okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSink.write(Http1ExchangeCodec.kt:303)
2022-04-05 09:30:57.901 4032-5187/com.example.storage_sample_new W/System.err:     at okio.ForwardingSink.write(ForwardingSink.kt:29)
2022-04-05 09:30:57.901 4032-5187/com.example.storage_sample_new W/System.err:     at okhttp3.internal.connection.Exchange$RequestBodySink.write(Exchange.kt:218)
2022-04-05 09:30:57.901 4032-5187/com.example.storage_sample_new W/System.err:     at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:255)
2022-04-05 09:30:57.901 4032-5187/com.example.storage_sample_new W/System.err:     at okio.RealBufferedSink.writeAll(RealBufferedSink.kt:194)
2022-04-05 09:30:57.901 4032-5187/com.example.storage_sample_new W/System.err:     at io.ktor.client.engine.okhttp.StreamRequestBody.writeTo(StreamRequestBody.kt:21)
2022-04-05 09:30:57.901 4032-5187/com.example.storage_sample_new W/System.err:     at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:59)
2022-04-05 09:30:57.901 4032-5187/com.example.storage_sample_new W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2022-04-05 09:30:57.901 4032-5187/com.example.storage_sample_new W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
2022-04-05 09:30:57.901 4032-5187/com.example.storage_sample_new W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2022-04-05 09:30:57.901 4032-5187/com.example.storage_sample_new W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
2022-04-05 09:30:57.901 4032-5187/com.example.storage_sample_new W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2022-04-05 09:30:57.901 4032-5187/com.example.storage_sample_new W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
2022-04-05 09:30:57.901 4032-5187/com.example.storage_sample_new W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2022-04-05 09:30:57.901 4032-5187/com.example.storage_sample_new W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
2022-04-05 09:30:57.901 4032-5187/com.example.storage_sample_new W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2022-04-05 09:30:57.901 4032-5187/com.example.storage_sample_new W/System.err:     at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
2022-04-05 09:30:57.901 4032-5187/com.example.storage_sample_new W/System.err:     at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
```

### Steps to Reproduce

Upload a large file using multipart upload api(s3.uploadPart{}) and observe part upload API response.

### Possible Solution

N/A

### AWS Kotlin SDK version used

0.14.1-beta

### Platform (JVM/JS/Native)

Native

### Operating System and version

Android 31

**Comment by aajtodd** [comment]
This was fixed as part of https://github.com/awslabs/smithy-kotlin/pull/620 and should be available in the next release

NOTE: You need to supply a `contentLength` still!

e.g.

```diff
private fun ByteStream.Companion.chunk(
        file: File,
        start: Long,
        length: Long
    ): ByteStream {
        return object : ByteStream.OneShotStream() {
+           override val contentLength: Long = length
            override fun readFrom(): SdkByteReadChannel {
                return file.readChannel(start, start + length - 1)
            }
        }
    }
```

**Comment by sdhuka** [comment]
@aajtodd I am still getting the same error after updating to 0.14.2-Beta. I have update the amplify code to use replayable streams to upload parts. Could you please look into it?

```
private fun ByteStream.Companion.chunk(
        file: File,
        start: Long,
        length: Long
    ): ByteStream {
        return object : ByteStream.ReplayableStream() {
            override val contentLength: Long = length
            override fun newReader(): SdkByteReadChannel {
                return file.readChannel(start, start + length - 1)
            }
        }
    }

```
```
2022-04-11 11:26:10.211 11732-11922/com.example.storage_sample_new W/System.err: [DefaultDispatcher-worker-18] WARN AwsSigv4SigningMiddleware - sdkRequestId: 7e5b3aa4-c720-4bae-95ab-0322dfcd0738; service: S3; operation: UploadPart; - unable to compute hash for unbounded stream; defaulting to unsigned payload
2022-04-11 11:26:10.221 11732-11922/com.example.storage_sample_new W/System.err: [DefaultDispatcher-worker-18] TRACE aws.smithy.kotlin.runtime.http.engine.ktor.KtorEngine - waiting on response to be available
2022-04-11 11:26:10.351 11732-11921/com.example.storage_sample_new W/System.err: [DefaultDispatcher-worker-17] ERROR aws.smithy.kotlin.runtime.http.engine.ktor.KtorEngine - throwing(java.net.SocketException: Broken pipe)
2022-04-11 11:26:10.352 11732-11921/com.example.storage_sample_new W/System.err: java.net.SocketException: Broken pipe
2022-04-11 11:26:10.352 11732-11921/com.example.storage_sample_new W/System.err:     at java.net.SocketOutputStream.socketWrite0(Native Method)
2022-04-11 11:26:10.352 11732-11921/com.example.storage_sample_new W/System.err:     at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:117)
2022-04-11 11:26:10.352 11732-11921/com.example.storage_sample_new W/System.err:     at java.net.SocketOutputStream.write(SocketOutputStream.java:161)
2022-04-11 11:26:10.352 11732-11921/com.example.storage_sample_new W/System.err:     at com.android.org.conscrypt.ConscryptEngineSocket$SSLOutputStream.writeToSocket(ConscryptEngineSocket.java:724)
2022-04-11 11:26:10.352 11732-11921/com.example.storage_sample_new W/System.err:     at com.android.org.conscrypt.ConscryptEngineSocket$SSLOutputStream.writeInternal(ConscryptEngineSocket.java:698)
2022-04-11 11:26:10.352 11732-11921/com.example.storage_sample_new W/System.err:     at com.android.org.conscrypt.ConscryptEngineSocket$SSLOutputStream.write(ConscryptEngineSocket.java:661)
2022-04-11 11:26:10.352 11732-11921/com.example.storage_sample_new W/System.err:     at okio.OutputStreamSink.write(JvmOkio.kt:53)
2022-04-11 11:26:10.352 11732-11921/com.example.storage_sample_new W/System.err:     at okio.AsyncTimeout$sink$1.write(AsyncTimeout.kt:103)
2022-04-11 11:26:10.352 11732-11921/com.example.storage_sample_new W/System.err:     at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:255)
2022-04-11 11:26:10.352 11732-11921/com.example.storage_sample_new W/System.err:     at okio.RealBufferedSink.write(RealBufferedSink.kt:146)
2022-04-11 11:26:10.352 11732-11921/com.example.storage_sample_new W/System.err:     at okhttp3.internal.http1.Http1ExchangeCodec$KnownLengthSink.write(Http1ExchangeCodec.kt:271)
2022-04-11 11:26:10.352 11732-11921/com.example.storage_sample_new W/System.err:     at okio.ForwardingSink.write(ForwardingSink.kt:29)
2022-04-11 11:26:10.352 11732-11921/com.example.storage_sample_new W/System.err:     at okhttp3.internal.connection.Exchange$RequestBodySink.write(Exchange.kt:218)
2022-04-11 11:26:10.352 11732-11921/com.example.storage_sample_new W/System.err:     at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:255)
2022-04-11 11:26:10.352 11732-11921/com.example.storage_sample_new W/System.err:     at okio.RealBufferedSink.writeAll(RealBufferedSink.kt:194)
2022-04-11 11:26:10.353 11732-11921/com.example.storage_sample_new W/System.err:     at io.ktor.client.engine.okhttp.StreamRequestBody.writeTo(StreamRequestBody.kt:21)
2022-04-11 11:26:10.353 11732-11921/com.example.storage_sample_new W/System.err:     at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:59)
2022-04-11 11:26:10.353 11732-11921/com.example.storage_sample_new W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2022-04-11 11:26:10.353 11732-11921/com.example.storage_sample_new W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
2022-04-11 11:26:10.353 11732-11921/com.example.storage_sample_new W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2022-04-11 11:26:10.353 11732-11921/com.example.storage_sample_new W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
2022-04-11 11:26:10.353 11732-11921/com.example.storage_sample_new W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2022-04-11 11:26:10.353 11732-11921/com.example.storage_sample_new W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
2022-04-11 11:26:10.353 11732-11921/com.example.storage_sample_new W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2022-04-11 11:26:10.353 11732-11921/com.example.storage_sample_new W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
2022-04-11 11:26:10.353 11732-11921/com.example.storage_sample_new W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2022-04-11 11:26:10.353 11732-11921/com.example.storage_sample_new W/System.err:     at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
2022-04-11 11:26:10.353 11732-11921/com.example.storage_sample_new W/System.err:     at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
2022-04-11 11:26:10.353 11732-11921/com.example.storage_sample_new W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2022-04-11 11:26:10.353 11732-11921/com.example.storage_sample_new W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2022-04-11 11:26:10.353 11732-11921/com.example.storage_sample_new W/System.err:     at java.lang.Thread.run(Thread.java:920)
```

**Comment by sdhuka** [comment]
This issue was resolved after fixing the chunk size. Thanks!!
